import json
import re

# Theme: The Alchemy of Fire & Spark (Cycle 53)
words_data = [
    ("ignition", "Ignition", "点火、発火、イグニッション", "17th Century", "in- (into, on) + gignere (to beget, literal: 'ignis' fire)", "The action of setting something on fire or starting to burn", "冷（。た（。い（。沈黙（。の中に（。、爆（。烈（。的な「火（。イグ）を（。産（。み（。出す（。）」こと（。。（。その（。一瞬の（。閃光（。が（。、眠（。って（。いた（。エナジーを（。、現在（。へと（。呼び（。覚（。ます（。のですよ。"),
    ("spark", "Spark", "火花、閃き、スパーク", "Old English", "spearca (spark)", "A small fiery particle thrown off from a fire, alight in ashes, or produced by striking together two hard objects such as stone or metal", "激（。しい（。衝突（。の（。果てに（。、闇（。を「引き（。裂（。く（。スぺ）」ように（。放た（。れた（。、光（。の（。小（。粒（。。（。それは（。、新しい（。真理が（。産（。声を（。上げる（。、最初（。の（。合図。"),
    ("flame", "Flame", "炎、情熱、フレイム", "14th Century", "phlama (flame, literal: 'phlegma' blaze)", "A hot luminous body of ignited gas that is generated by something on fire", "物質（。が（。エナジーへと（。還（。る（。ときに（。、激しく「揺（。れ（。動（。く（。フラ）」姿（。。（。その（。眩（。し（。い（。熱は（。、周囲（。の（。全（。てを（。、愛（。という（。名の（。光で（。包（。み（。込む（。のです。"),
    ("forge", "Forge", "鍛造する、作り上げる、フォージ", "13th Century", "fabrica (workshop)", "Make or shape by heating it in a fire or furnace and beating or hammering it", "ただ（。作る（。のではなく（。、烈（。しい「火（。の（。中で（。ファ）」、困難（。を（。潜（。り（。抜け（。て（。、ようやく（。形（。作（。られる（。もの（。。（。打（。た（。れる（。ことで（。強（。味（。を（。増（。す（。、魂の（。結晶。"),
    ("weld", "Weld", "溶接する、統合する", "16th Century", "wellen (to boil, flow)", "Join by heating the surfaces to the point of melting using a blowpipe, electric arc, or other means, and uniting them by pressing, hammering, etc.", "バラバラ（。の（。個体（。を（。、一度「煮（。え（。湯（。ウェル）」のように（。溶（。かし（。合い（。、一（。つ（。の（。塊（。へと（。至（。る（。こと（。。（。もう（。二（。度（。と（。離（。れ（。ら（。れ（。ない（。、鋼（。の（。ような（。意志の（。結合。"),
    ("fuse", "Fuse", "融合する、導火線、フューズ", "17th Century", "fundere (to pour)", "Join or blend to form a single entity", "境界線（。を（。溶（。か（。し（。、互い（。のエナジーを「注（。ぎ（。込（。み（。合う（。フュ）」こと（。。（。異純（。な（。もの（。同士が（。、混ざり（。合った（。とき（。、全（。く（。新（。しい（。輝（。きが（。産（。ま（。れる（。のですよ。"),
    ("vaporize", "Vaporize", "蒸発させる、消失させる", "18th Century", "vapor (mist, steam)", "Convert or be converted into vapor", "固（。執（。し（。て（。いた（。重い（。かたち（。を（。捨て（。去り（。、ただの「霧（。ヴァポー）」と（。なって（。、空（。へと（。溶（。け（。込んで（。行く（。こと（。。（。未（。練（。さえ（。も（。エナジーへと（。還（。す（。、光（。の（。昇（。華。"),
    ("distill", "Distill", "蒸留する、抽出する", "14th Century", "de- (down) + stillare (to drop, drip)", "Purify by a process of heating and cooling", "余計（。な（。混（。じ（。り（。物（。を（。削（。ぎ（。落（。し（。、ただ「一（。滴（。ずつ（。スティラ）した（。たり（。落ち（。る（。デ）」真理に（。まで（。純（。化（。する（。こと（。。（。最後（。に残った（。その（。一滴（。にこそ（。、全（。宇宙の（。智（。恵が（。宿（。って（。いる（。の（。ですよ。"),
    ("refine", "Refine", "洗練する、精製する", "16th Century", "re- (intensive) + fin (limit, end, fine)", "Remove impurities or unwanted elements from, typically as part of an industrial process", "終わりの（。ない（。努力（。を「繰（。り（。返（。し（。リ）究（。め（。る（。ファイン）」こと（。。（。研（。ぎ（。澄（。ま（。さ（。れ（。た（。その（。姿は（。、ただ（。存在（。する（。だけで（。、周囲（。に（。気高（。い（。光を（。放（。ち（。ます。"),
    ("kinetic", "Kinetic", "動的な、運動の、キネティック", "19th Century", "kinein (to move)", "Relating to or resulting from motion", "ただ（。そこに（。ある（。だけでなく（。、常に「動（。き（。キネ）続けて（。いる（。）」こと（。。（。生命（。とは（。、一瞬（。の（。休止（。もなく（。、未来（。へと（。跳（。躍（。し（。続ける（。、エナジーの（。ダンス（。なの（。ですよ。"),
    ("dynamic", "Dynamic", "力強い、ダイナミック", "19th Century", "dunasteia (power, might)", "Characterized by constant change, activity, or progress", "停滞（。を（。嫌（。い（。、内側（。から（。溢（。れ（。出る（。圧倒（。的な「力（。デュナ）」に（。身（。を（。任（。せる（。こと（。。（。その（。力強い（。拍動が（。、世界（。の（。壁（。を（。打（。ち（。破（。って（。いく（。のです。"),
    ("friction", "Friction", "摩擦、不和、フリクション", "16th Century", "fricare (to rub)", "The resistance that one surface or object encounters when moving over another", "互（。いに（。譲（。ら（。ない（。魂が（。、激しく「擦（。れ（。合う（。フリカ）」こと（。。（。その（。鋭（。い（。熱（。が（。、いつか（。新しい（。希望（。の（。火（。を（。点（。す（。、聖（。なる（。試練（。なの（。ですよ。"),
    ("acceleration", "Acceleration", "加速、促進、アクセラレーション", "16th Century", "ad- (to) + celerare (to hasten, literal: keler swift)", "A vehicle's capacity to gain speed within a short time", "昨日（。までの（。自分（。を（。追いこ（。し（。、より「速（。い（。ケレ）領域（。へと（。アド）」至（。ろう（。とする（。こと（。。（。一度（。始（。まった（。飛翔（。は（。、もう（。誰（。にも（。止（。め（。られ（。ない（。のですよ。"),
    ("torque", "Torque", "トルク、回転力", "19th Century", "torquere (to twist)", "A twisting force that tends to cause rotation", "真っ直ぐ（。な（。エナジーを（。、あえて「ねじ（。折（。る（。トルク）」ように（。回転（。させる（。力（。。（。その（。複雑（。な（。う（。ねり（。が（。、鉄（。をも（。易（。々と（。貫（。く（。、深（。淵なる（。引力（。を（。産（。み出す（。のです。"),
    ("pulse", "Pulse", "脈動、パルス", "14th Century", "pellere (to drive, push)", "A rhythmical throbbing of the arteries as blood is propelled through them by the contractions of the heart", "一定（。のリズム（。を（。持って（。、エナジーを（。外（。へと「突（。き（。出す（。パル）」こと（。。（。あなたが（。生きて（。いる（。という（。、たった（。一つ（。の（。無（。言（。の（。、けれど（。（。確（。かな（。力説。")
]

def run_cycle():
    file_path = r'c:\Users\integ\OneDrive\デスクトップ\ling-ling-etymon\data.js'
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        match = re.search(r'(const WORDS = )(\[.*\])(;)', content, re.DOTALL)
        if not match:
            print("Error: Could not find WORDS array in data.js")
            return

        prefix, json_array_str, suffix = match.groups()
        existing_words = json.loads(json_array_str)
        existing_ids = {w.get("id") for w in existing_words}
        existing_word_texts = {w.get("word").lower() for w in existing_words}

        added_count = 0
        for item in words_data:
            word_text = item[0]
            word_id = f"{word_text.lower()}_fire"
            
            if word_id not in existing_ids and word_text.lower() not in existing_word_texts:
                new_word = {
                    "id": word_id,
                    "word": word_text,
                    "meaning": item[2],
                    "era": item[3],
                    "etymology": {
                        "components": [item[4]],
                        "original_statement": f"From {item[3]} {item[4]}."
                    },
                    "concept": item[5] + f" ({item[6]})",
                    "thinking": item[6],
                    "aftertaste": item[7] if len(item) > 7 else "火は、物質が自らの重みを捨て去り、光へと還るための、激しい祈りの儀式です。",
                    "example": f"The engine's {word_text} system was carefully designed to maximize fuel efficiency.",
                    "deep_dive": {
                        "roots": [{"term": item[4].split(" ")[0] if " " in item[4] else item[4], "meaning": " ".join(item[4].split(" ")[1:]).strip("()") if " " in item[4] else "origin"}],
                        "points": ["熱とは、静止した世界を再び流動させるための、魂の拍動なのです。"]
                    },
                    "part_of_speech": "noun" if item[0] not in ["kinetic", "dynamic"] else "adjective"
                }
                existing_words.append(new_word)
                added_count += 1
                existing_ids.add(word_id)
                existing_word_texts.add(word_text.lower())

        new_json_str = json.dumps(existing_words, ensure_ascii=False, indent='\t')
        new_content = content[:match.start()] + prefix + new_json_str + suffix + content[match.end():]

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)

        print(f"Success: Added {added_count} words. Theme: Fire & Spark (Cycle 53).")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    run_cycle()
